from dotenv import load_dotenv
import os

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
SECRET_KEY = os.getenv("SECRET_KEY")
QUESTRADE_SERVER = os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES")
WSIMPLE_EMAIL = os.getenv("WSIMPLE_EMAIL")
WSIMPLE_PASSWORD = os.getenv("WSIMPLE_PASSWORD")
QUESTRADE_REFRESH_TOKEN = os.getenv("QUESTRADE_REFRESH_TOKEN")
WSIMPLE_REFRESH_TOKEN = os.getenv("WSIMPLE_REFRESH_TOKEN")
QUESTRADE_ACCESS_TOKEN = os.getenv("QUESTRADE_ACCESS_TOKEN")
